### PR TITLE
Fix #35; Replace marisa-trie with pygtrie

### LINKED ISSUE #35: Alternative trie dependency?
This project depends on [marisa-trie](https://github.com/pytries/marisa-trie), which is a Cython/C++ extension module. The [latest release](https://pypi.org/project/marisa-trie/0.7.5/#files) from 2.5 years ago only has pre-built binaries for Python3.6 on macOS, and there are no releases with binaries for a newer version of Python than 3.6. This means users must build it from source, which requires them to have a compiler, the Python development headers, etc. installed. I created [this issue](https://github.com/pytries/marisa-trie/issues/57) but haven't gotten a response from the marisa-trie devs.

Would you be receptive to using a more active project, like [datrie](https://github.com/pytries/datrie), or a pure-Python one like [pygtrie](https://github.com/mina86/pygtrie)?

I'm wary to distribute software that depends on langcodes because of the problems with the marisa-trie dependency.

### PR DESCRIPTION
**Pull request by goodmami**
This replaces the marisa-trie dependency with the pure-Python pygtrie one. All `.marisa` files have been converted to compressed JSON files. Running `example.py` takes roughly 4x longer than with marisa-trie, but the disk space requirements of the JSON files (when compressed) are reduced a bit. The purpose of the switch to pygtrie is that marisa-trie does not have wheels built for newer Python versions or for non-macOS platforms, which makes the installation of langcodes difficult for some.

The changes in `build_data.py` have not been tested. The data was converted using the following script, adapted from user ygorg's script in #35:

```python
import json
import gzip
from glob import glob

import marisa_trie

base = 'langcodes/data/trie'

for fn in glob(base + '/*.marisa') + glob(base + '/*/*.marisa'):
    trie = marisa_trie.BytesTrie()
    trie.load(fn)
    dd = {k: v.decode('utf-8') if type(v) is bytes else v for k, v in trie.items()}
    with gzip.open(fn.replace('marisa', 'json.gz'), 'wt', encoding='utf-8') as f:
        f.write(json.dumps(dd), f)
```

### CODE REVIEW

**Comment by nyuszika7h** [comment]
Could also use `marisa-trie-m` which is compatible with Python 3.9.

**Comment by rspeer** [comment]
Hi, thanks for the PR! I've been on break, sorry that I haven't been responding.

I do see that the dependency on marisa-trie has caused problems. Using a pure Python trie sounds like a good way out, and a 4x slowdown sounds acceptable. I'll take a look.

**Comment by rspeer** [comment]
After trying it out, I'm not convinced this is quite the solution. I'm noticing a large delay when loading each of the name tries (language_to_name, territory_to_name, script_to_name) from JSON. Even though the example script iterates over lots of names quickly, this delay will happen on the first lookup in every process, which might be, for example, a Web server process that's rendering a list of language choices.

I recognize that this is the fault of the design of langcodes, and slowing down loading just makes it much more noticeable.

Now, there's not so much of a reason that the `*_to_name` data structures have to be tries. I believe my reason for using tries was that they were well-suited for the `name_to_*` case, and then I just reused them for this. It's possible that we could load some plain old dictionaries, like the ones in `data_dicts.py`, for the case of converting codes to names.

**Comment by nyuszika7h** [comment]
Maybe you could use [marisa-trie-m](https://pypi.org/project/marisa-trie-m/).

**Comment by goodmami** [comment]
@rspeer sounds reasonable. With #37 merged, I think this one can be closed?

**Pull request closed without merging**
