### PR TITLE
Fixed multi-threading issue with sqlite

### PR DESCRIPTION
**Pull request by darkman66**
There is serious problem with this module when you try to use it with code working in multi-threaded model. By using semaphore I tricked sqlite engine so it thinks that one thread a time accesses db hook.

Also tested with multiprocessing - works.

### CODE REVIEW

**Comment by rspeer** [comment]
Ah, okay. Apparently I misunderstood the sqlite3 documentation -- I thought it was okay to use it in multiple threads if I was just reading.

The change looks good, I'll just want to clean up the documentation a bit.

**Comment by rspeer** [comment]
Okay, I'm looking at this again. If you're still available to answer this, darkman66: what is the problem that's being solved by `threading.Condition()`? I want to understand what's going on and know what the extra thread-related code is doing.

The impression I had before was that it was safe to read a database from multiple threads, as long as nothing was writing. And that's going to be the case for langcodes, because the langcodes database doesn't change.

There's a lot of stuff that wraps the code that *writes* to the database. This is something that happens once, in a build process, and I can't imagine why it would need to be threaded. Is this where the threading problem occurred?

**Comment by darkman66** [comment]
Here is simple example. Try to run twisted app in multithreaded system where you're playing with sqlite by using the same connection hook. By nature of sqlite YOU CAN NOT access it from many threads in the same time (reading same as writing). My binary semaphore is just locking access o db cursor on python level so many threads coming from the same process do not compete with each other the exclusive access to DB connection hook.

https://www.sqlite.org/threadsafe.html

"Multi-thread. In this mode, SQLite can be safely used by multiple threads provided that no single database connection is used simultaneously in two or more threads." :+1:

**Comment by rspeer** [comment]
Hmm, I see. I recognize there's a problem here. http://stackoverflow.com/questions/13912489/read-only-access-only-for-sqlite3-from-multiple-threads explains the issue.

I still have some questions, though, because I'd like to know what the code is doing.

Are the calls to `Condition.notify_all` actually necessary if nothing ever calls `Condition.wait`? What is being notified?

Also, if this is supposed to work in Twisted, how are you planning to disable the same-thread check in Python 2?

**Comment by darkman66** [comment]
Actually notifyAll is not that much needed here, true.

As for "how it works" please read semaphores

**Comment by rspeer** [comment]
I've neglected this PR for a while, but the upshot is that I don't believe it works.

My understanding is that semaphores are not the same as locks. You've used semaphores here, but those are not described as "stopping many threads from accessing sensitive code blocks" in the documentation at https://docs.python.org/3/library/threading.html. That would be a job for locks. 

Semaphores are about sending notifications between threads, to coordinate timing, but nothing is ever listening to the notifications here.

This also does not seem to fix the "same-thread check" that is required on Python 2 and default on Python 3, which stops you from accessing a SQLite DB from multiple threads at all.

I think I would rather have langcodes simply not be thread-safe than to claim to be thread safe based on code that doesn't seem to actually implement thread safety.

**Comment by rspeer** [comment]
As a follow-up, the underlying problem has been fixed in Python 3.5: https://docs.python.org/3.5/library/sqlite3.html

> By default, check_same_thread is True and only the creating thread may use the connection. If set False, the returned connection may be shared across multiple threads. When using multiple threads with the same connection writing operations should be serialized by the user to avoid data corruption.

Now only write operations need to be serialized.

**Pull request closed without merging**
